"""
API request and response schemas.
"""

from .auth import (
    LoginRequest,
    RegisterRequest,
    TokenResponse,
    UserResponse,
    PasswordResetRequest,
    PasswordResetConfirm,
    PasswordChangeRequest,
    RefreshTokenRequest,
)

from .content import (
    OutlineSectionSchema,
    OutlineCreateRequest,
    OutlineUpdateRequest,
    OutlineResponse,
    OutlineListResponse,
    ArticleCreateRequest,
    ArticleGenerateRequest,
    ArticleUpdateRequest,
    ArticleResponse,
    ArticleListResponse,
    ArticleImproveRequest,
    ArticleSEOAnalysis,
    ImageGenerateRequest,
    ImageResponse,
    ImageListResponse,
)

from .wordpress import (
    WordPressConnectRequest,
    WordPressConnectionResponse,
    WordPressPublishRequest,
    WordPressPublishResponse,
    WordPressCategoryResponse,
    WordPressTagResponse,
    WordPressDisconnectResponse,
)

from .analytics import (
    GSCConnectResponse,
    GSCCallbackRequest,
    GSCConnectionStatus,
    GSCSiteResponse,
    GSCSiteListResponse,
    GSCSelectSiteRequest,
    GSCSyncResponse,
    GSCDisconnectResponse,
    KeywordRankingResponse,
    KeywordRankingListResponse,
    PagePerformanceResponse,
    PagePerformanceListResponse,
    DailyAnalyticsResponse,
    DailyAnalyticsListResponse,
    AnalyticsSummaryResponse,
    TrendData,
    DateRangeParams,
)

from .billing import (
    PlanLimits,
    PlanInfo,
    PricingResponse,
    SubscriptionStatus,
    CheckoutRequest,
    CheckoutResponse,
    CustomerPortalResponse,
    SubscriptionCancelResponse,
    WebhookEventType,
)

from .knowledge import (
    SourceUploadResponse,
    KnowledgeSourceResponse,
    KnowledgeSourceListResponse,
    KnowledgeSourceUpdateRequest,
    QueryRequest,
    QueryResponse,
    SourceSnippet,
    KnowledgeStatsResponse,
    ReprocessRequest,
    ReprocessResponse,
)

from .social import (
    ConnectAccountResponse,
    SocialAccountResponse,
    SocialAccountListResponse,
    DisconnectAccountResponse,
    VerifyAccountResponse,
    PostTargetRequest,
    CreatePostRequest,
    UpdatePostRequest,
    PostTargetResponse,
    ScheduledPostResponse,
    ScheduledPostListResponse,
    CalendarDayPost,
    CalendarDay,
    CalendarResponse,
    PlatformAnalytics,
    PostAnalyticsResponse,
    PreviewRequest,
    PlatformLimits,
    PreviewResponse,
    BestTimeSlot,
    BestTimesResponse,
)

from .admin_content import (
    AdminArticleAuthorInfo,
    AdminArticleListItem,
    AdminArticleListResponse,
    AdminArticleDetail,
    AdminOutlineListItem,
    AdminOutlineListResponse,
    AdminImageListItem,
    AdminImageListResponse,
    AdminSocialPostListItem,
    AdminSocialPostListResponse,
    BulkDeleteRequest,
    BulkDeleteResponse,
    DeleteResponse,
)

from .admin import (
    DashboardStatsResponse,
    UserStats,
    ContentStats,
    SubscriptionStats,
    RevenueStats,
    TimeSeriesData,
    UserAnalyticsResponse,
    SignupTrend,
    RetentionMetrics,
    ConversionMetrics,
    GeographicDistribution,
    ContentAnalyticsResponse,
    ContentTrend,
    TopUser,
    ContentStatusBreakdown,
    RevenueAnalyticsResponse,
    MonthlyRevenue,
    SubscriptionDistribution,
    ChurnIndicator,
    SystemHealthResponse,
    TableStats,
    StorageStats,
    ErrorRate,
    BackgroundJobStatus,
    UserUpdateRequest,
    SuspendUserRequest,
    UnsuspendUserRequest,
    PasswordResetRequest as AdminPasswordResetRequest,
    UsageStatsResponse,
    UserDetailResponse,
    UserListItemResponse,
    UserListResponse,
    AdminUserInfo,
    AuditLogResponse,
    AuditLogListResponse,
    UserListFilters,
    AuditLogFilters,
    UserActionResponse,
    DeleteUserResponse,
)

from .project_billing import (
    ProjectLimits,
    ProjectUsageStats,
    ProjectSubscriptionResponse,
    ProjectCheckoutRequest,
    ProjectCheckoutResponse,
    ProjectPortalResponse,
    ProjectCancelResponse,
    ProjectUsageResponse,
)

from .project import (
    ProjectCreate,
    ProjectUpdate,
    ProjectResponse,
    ProjectListResponse,
    ProjectMemberAdd,
    ProjectMemberUpdate,
    ProjectMemberResponse,
    ProjectMemberListResponse,
    ProjectInvitationCreate,
    ProjectInvitationResponse,
    ProjectInvitationListResponse,
    ProjectInvitationAccept,
    ProjectInvitationPublicResponse,
    ProjectInvitationAcceptResponse,
    ProjectStats,
    ProjectSettings,
    ProjectSwitchRequest,
    ProjectSwitchResponse,
)

__all__ = [
    # Auth
    "LoginRequest",
    "RegisterRequest",
    "TokenResponse",
    "UserResponse",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    "PasswordChangeRequest",
    "RefreshTokenRequest",
    # Content
    "OutlineSectionSchema",
    "OutlineCreateRequest",
    "OutlineUpdateRequest",
    "OutlineResponse",
    "OutlineListResponse",
    "ArticleCreateRequest",
    "ArticleGenerateRequest",
    "ArticleUpdateRequest",
    "ArticleResponse",
    "ArticleListResponse",
    "ArticleImproveRequest",
    "ArticleSEOAnalysis",
    "ImageGenerateRequest",
    "ImageResponse",
    "ImageListResponse",
    # WordPress
    "WordPressConnectRequest",
    "WordPressConnectionResponse",
    "WordPressPublishRequest",
    "WordPressPublishResponse",
    "WordPressCategoryResponse",
    "WordPressTagResponse",
    "WordPressDisconnectResponse",
    # Analytics
    "GSCConnectResponse",
    "GSCCallbackRequest",
    "GSCConnectionStatus",
    "GSCSiteResponse",
    "GSCSiteListResponse",
    "GSCSelectSiteRequest",
    "GSCSyncResponse",
    "GSCDisconnectResponse",
    "KeywordRankingResponse",
    "KeywordRankingListResponse",
    "PagePerformanceResponse",
    "PagePerformanceListResponse",
    "DailyAnalyticsResponse",
    "DailyAnalyticsListResponse",
    "AnalyticsSummaryResponse",
    "TrendData",
    "DateRangeParams",
    # Billing
    "PlanLimits",
    "PlanInfo",
    "PricingResponse",
    "SubscriptionStatus",
    "CheckoutRequest",
    "CheckoutResponse",
    "CustomerPortalResponse",
    "SubscriptionCancelResponse",
    "WebhookEventType",
    # Knowledge
    "SourceUploadResponse",
    "KnowledgeSourceResponse",
    "KnowledgeSourceListResponse",
    "KnowledgeSourceUpdateRequest",
    "QueryRequest",
    "QueryResponse",
    "SourceSnippet",
    "KnowledgeStatsResponse",
    "ReprocessRequest",
    "ReprocessResponse",
    # Social
    "ConnectAccountResponse",
    "SocialAccountResponse",
    "SocialAccountListResponse",
    "DisconnectAccountResponse",
    "VerifyAccountResponse",
    "PostTargetRequest",
    "CreatePostRequest",
    "UpdatePostRequest",
    "PostTargetResponse",
    "ScheduledPostResponse",
    "ScheduledPostListResponse",
    "CalendarDayPost",
    "CalendarDay",
    "CalendarResponse",
    "PlatformAnalytics",
    "PostAnalyticsResponse",
    "PreviewRequest",
    "PlatformLimits",
    "PreviewResponse",
    "BestTimeSlot",
    "BestTimesResponse",
    # Admin Content
    "AdminArticleAuthorInfo",
    "AdminArticleListItem",
    "AdminArticleListResponse",
    "AdminArticleDetail",
    "AdminOutlineListItem",
    "AdminOutlineListResponse",
    "AdminImageListItem",
    "AdminImageListResponse",
    "AdminSocialPostListItem",
    "AdminSocialPostListResponse",
    "BulkDeleteRequest",
    "BulkDeleteResponse",
    "DeleteResponse",
    # Admin Analytics
    "DashboardStatsResponse",
    "UserStats",
    "ContentStats",
    "SubscriptionStats",
    "RevenueStats",
    "TimeSeriesData",
    "UserAnalyticsResponse",
    "SignupTrend",
    "RetentionMetrics",
    "ConversionMetrics",
    "GeographicDistribution",
    "ContentAnalyticsResponse",
    "ContentTrend",
    "TopUser",
    "ContentStatusBreakdown",
    "RevenueAnalyticsResponse",
    "MonthlyRevenue",
    "SubscriptionDistribution",
    "ChurnIndicator",
    "SystemHealthResponse",
    "TableStats",
    "StorageStats",
    "ErrorRate",
    "BackgroundJobStatus",
    # Admin User Management
    "UserUpdateRequest",
    "SuspendUserRequest",
    "UnsuspendUserRequest",
    "AdminPasswordResetRequest",
    "UsageStatsResponse",
    "UserDetailResponse",
    "UserListItemResponse",
    "UserListResponse",
    "AdminUserInfo",
    "AuditLogResponse",
    "AuditLogListResponse",
    "UserListFilters",
    "AuditLogFilters",
    "UserActionResponse",
    "DeleteUserResponse",
    # Project Billing
    "ProjectLimits",
    "ProjectUsageStats",
    "ProjectSubscriptionResponse",
    "ProjectCheckoutRequest",
    "ProjectCheckoutResponse",
    "ProjectPortalResponse",
    "ProjectCancelResponse",
    "ProjectUsageResponse",
    # Project Management
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectListResponse",
    "ProjectMemberAdd",
    "ProjectMemberUpdate",
    "ProjectMemberResponse",
    "ProjectMemberListResponse",
    "ProjectInvitationCreate",
    "ProjectInvitationResponse",
    "ProjectInvitationListResponse",
    "ProjectInvitationAccept",
    "ProjectInvitationPublicResponse",
    "ProjectInvitationAcceptResponse",
    "ProjectStats",
    "ProjectSettings",
    "ProjectSwitchRequest",
    "ProjectSwitchResponse",
]
