import type { Metadata } from "next";
import LandingPageClient from "@/components/landing/LandingPageClient";
import { locales } from "@/i18n/config";

const SITE_URL = "https://a-stats.app";

export const metadata: Metadata = {
  title: "A-Stats — AI Content & SEO Platform | Rank on Google + AI Engines",
  description:
    "Generate SEO-optimized articles, track rankings, and monitor AEO scores with AI. From keyword to published article in minutes.",
  alternates: {
    canonical: SITE_URL,
    languages: Object.fromEntries(
      locales.map((locale) => [locale, `${SITE_URL}/${locale}`])
    ),
  },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "SoftwareApplication",
      name: "A-Stats",
      applicationCategory: "BusinessApplication",
      operatingSystem: "Web",
      url: SITE_URL,
      description:
        "AI-powered SEO content creation and optimization platform. Generate articles, track rankings, and optimize for AI answer engines.",
      aggregateRating: {
        "@type": "AggregateRating",
        ratingValue: "4.8",
        ratingCount: "127",
        bestRating: "5",
        worstRating: "1",
      },
      offers: [
        {
          "@type": "Offer",
          name: "Free",
          price: "0",
          priceCurrency: "USD",
          availability: "https://schema.org/InStock",
        },
        {
          "@type": "Offer",
          name: "Starter",
          price: "29.00",
          priceCurrency: "USD",
          availability: "https://schema.org/InStock",
          priceValidUntil: "2026-12-31",
        },
        {
          "@type": "Offer",
          name: "Professional",
          price: "79.00",
          priceCurrency: "USD",
          availability: "https://schema.org/InStock",
          priceValidUntil: "2026-12-31",
        },
        {
          "@type": "Offer",
          name: "Enterprise",
          price: "199.00",
          priceCurrency: "USD",
          availability: "https://schema.org/InStock",
          priceValidUntil: "2026-12-31",
        },
      ],
    },
    {
      "@type": "FAQPage",
      mainEntity: [
        {
          "@type": "Question",
          name: "Is there a free trial?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes. Every account starts on the free tier with no credit card required. You get 3 articles, 3 images, and 5 social posts per month to explore the platform before upgrading. No time limit on the free tier.",
          },
        },
        {
          "@type": "Question",
          name: "Can I cancel my subscription anytime?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes. There are no contracts or cancellation fees. You can downgrade or cancel from your account settings at any time. Your content stays accessible even after downgrading.",
          },
        },
        {
          "@type": "Question",
          name: "Who owns the content generated by A-Stats?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "You do — 100%. All content generated on our platform belongs to you to publish, repurpose, or sell. We never claim rights over your generated articles, images, or social posts.",
          },
        },
        {
          "@type": "Question",
          name: "What is Answer Engine Optimization (AEO)?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Answer Engine Optimization (AEO) is the practice of structuring and optimizing your content so it gets cited by AI-powered answer engines like ChatGPT, Perplexity, Google AI Overviews, and Microsoft Copilot. Unlike traditional SEO which focuses on ranking in search results, AEO focuses on making your content the source that AI systems reference when answering user questions. A-Stats tracks your AEO score (0-100) for each page, monitors when AI engines start or stop citing your content, and provides recommendations to improve your answer-readiness. This is increasingly important as more users get answers directly from AI instead of clicking through to websites.",
          },
        },
        {
          "@type": "Question",
          name: "Does A-Stats integrate with WordPress?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes. Connect your WordPress site using an application password in your settings. Once linked, you can publish articles directly from A-Stats complete with formatting, featured images, SEO metadata, and schema markup. The integration supports WordPress 5.6+ with HTTPS.",
          },
        },
        {
          "@type": "Question",
          name: "What languages are supported?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "A-Stats supports content generation in English, Spanish, French, German, Romanian, and more languages are being added regularly. The platform interface is available in all five languages. Articles are generated using native-speaking AI models for natural, fluent output in each language.",
          },
        },
        {
          "@type": "Question",
          name: "What AI models does A-Stats use?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "A-Stats uses a multi-model AI pipeline for the best results at each stage: Google Gemini for keyword research and SERP analysis, GPT-4o for content outline generation, and Claude for full article writing. This approach ensures each AI model is used where it performs best, resulting in higher-quality, more accurate content.",
          },
        },
        {
          "@type": "Question",
          name: "How is A-Stats different from Jasper or SurferSEO?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "A-Stats is an all-in-one platform that combines AI content generation, SEO analytics, AEO tracking, social media scheduling, and WordPress publishing in a single tool. Unlike Jasper (which focuses on writing) or SurferSEO (which focuses on optimization), A-Stats covers the full content lifecycle from keyword research to published article to performance tracking. Plus, A-Stats is the first platform to offer Answer Engine Optimization (AEO) tracking — monitoring when AI systems cite your content.",
          },
        },
      ],
    },
  ],
};

export default function HomePage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <LandingPageClient />
    </>
  );
}
