import type { Metadata } from "next";
import LandingPageClient from "@/components/landing/LandingPageClient";

export const metadata: Metadata = {
  title: "A-Stats — Create Content That Ranks",
  description:
    "Generate SEO-optimized articles, track keyword rankings, monitor AEO scores, and scale your content production with AI. From keyword to published article in minutes.",
};

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "SoftwareApplication",
      name: "A-Stats",
      applicationCategory: "BusinessApplication",
      operatingSystem: "Web",
      url: "https://a-stats.app",
      description:
        "AI-powered SEO content creation and optimization platform. Generate articles, track rankings, and optimize for AI answer engines.",
      offers: [
        {
          "@type": "Offer",
          name: "Starter",
          price: "29.00",
          priceCurrency: "USD",
        },
        {
          "@type": "Offer",
          name: "Professional",
          price: "79.00",
          priceCurrency: "USD",
        },
        {
          "@type": "Offer",
          name: "Enterprise",
          price: "199.00",
          priceCurrency: "USD",
        },
      ],
    },
    {
      "@type": "FAQPage",
      mainEntity: [
        {
          "@type": "Question",
          name: "Is there a free trial?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes. Every account starts on the free tier with no credit card required. You can generate articles and explore the platform before upgrading.",
          },
        },
        {
          "@type": "Question",
          name: "Can I cancel my subscription anytime?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes. There are no contracts or cancellation fees. You can downgrade or cancel from your account settings at any time.",
          },
        },
        {
          "@type": "Question",
          name: "Who owns the content generated by A-Stats?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "You do — 100%. All content generated on our platform belongs to you to publish, repurpose, or sell.",
          },
        },
        {
          "@type": "Question",
          name: "What is Answer Engine Optimization (AEO)?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "AEO is the practice of optimizing your content to be cited by AI systems like ChatGPT, Perplexity, and Google AI Overviews. A-Stats tracks your AEO score and alerts you when AI engines start or stop citing your pages.",
          },
        },
        {
          "@type": "Question",
          name: "Does A-Stats integrate with WordPress?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes. Connect your WordPress site in your project settings. Once linked, you can publish articles directly from the A-Stats editor complete with formatting, images, and metadata.",
          },
        },
        {
          "@type": "Question",
          name: "What languages are supported?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "A-Stats supports content generation in English, Spanish, French, German, Romanian, and more languages are being added regularly.",
          },
        },
      ],
    },
  ],
};

export default function HomePage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <LandingPageClient />
    </>
  );
}
